### ISSUE TITLE
Difficulty clicking on a dot in the brain view when it has multiple links to other dots.

### ISSUE THREAD

**Issue by vbruick** [varunbhoopalam/slipbox#38]
I have a note linked to four other notes. In the brain view, if I try to click on the dot, it only works when I hover over the little bit of blue dot that is visible. It does not work if I click on the black lines.

**Comment by varunbhoopalam** [comment]
Thank you for submitting an issue! I sincerely appreciate it. I've identified a solution and will implement it now
